global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'q-opsec-python'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - '192.168.18.18:8000' # risk
          - '192.168.18.18:8001' # handshake
          - '192.168.18.18:8002' # kms
          - '192.168.18.18:8003' # kde
          - '192.168.18.18:8004' # crypto
          - '192.168.18.18:8083' # confiability
          - '192.168.18.18:8088' # classification
          - '192.168.18.18:9009' # rl_engine

  - job_name: 'q-opsec-java'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - '192.168.18.18:8080'  # interceptor
          - '192.168.18.18:65534' # context
          - '192.168.18.18:8005'  # validation
