global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'q-opsec-python'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - '192.168.18.18:8000'
          - '192.168.18.18:8001'
          - '192.168.18.18:8002'
          - '192.168.18.18:8003'
          - '192.168.18.18:8004'
          - '192.168.18.18:8083'
          - '192.168.18.18:8088'
          - '192.168.18.18:9009'

  - job_name: 'q-opsec-java'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - '192.168.18.18:8080'
          - '192.168.18.18:65534'
          - '192.168.18.18:8005'
